package com.milabuda.redditconnector.api.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
public record Post(
        Long approvedAtUtc,
        String subreddit,
        String selftext,
        String authorFullname,
        Long createdAt,
        Long createdUtc,
        boolean saved,
        String modReasonTitle,
        Integer gilded,
        boolean clicked,
        String title,
        List<LinkFlair> linkFlairRichtext,
        String subredditNamePrefixed,
        boolean hidden,
        Integer pwls,
        String linkFlairCssClass,
        Integer downs,
        String thumbnail,
        Integer thumbnailHeight,
        Integer thumbnailWidth,
        String topAwardedType,
        boolean hideScore,
        String name,
        boolean quarantine,
        String linkFlairTextColor,
        Double upvoteRatio,
        String authorFlairBackgroundColor,
        String subredditType,
        Integer ups,
        Integer totalAwardsReceived,
        Map<String, Object> mediaEmbed,
        String authorFlairTemplateId,
        String authorFlairCssClass,
        List<Object> authorFlairRichtext,
        Map<String, Object> gildings,
        String contentCategories,
        boolean isSelf,
        String domain,
        String linkFlairText,
        boolean canModPost,
        Integer score,
        boolean isCreatedFromAdsUi,
        boolean authorPremium,
        String edited,
        boolean locked,
        String modNote,
        Object approvedBy,
        boolean isCrosspostable,
        boolean pinned,
        boolean over18,
        List<Object> allAwardings,
        List<Object> awarders,
        boolean mediaOnly,
        boolean spoiler,
        String removalReason,
        Object bannedBy,
        String authorFlairType,
        Integer subredditSubscribers,
        boolean isRobotIndexable,
        boolean isOriginalContent,
        String permalink,
        Integer numComments,
        String url,
        String id,
        String author,
        boolean contestMode,
        boolean sendReplies,
        boolean isVideo
) {
}
